/**
    * @description      : 
    * @author           : 
    * @group            : 
    * @created          : 16/04/2023 - 06:03:39
    * 
    * MODIFICATION LOG
    * - Version         : 1.0.0
    * - Date            : 16/04/2023
    * - Author          : 
    * - Modification    : 
**/
// Generated by https://quicktype.io

export interface NewTumblApiResponse {
    nResult: string;
    aResultSet: AResultSet[];
}

export interface AResultSet {
    aRow: ARow[];
    nTotalRows: number;
    aField: AField[];
}

export interface AField {
    sName: string;
    oMin: number | string;
    oMax: number | string;
    sType: string;
    bNumeric: boolean;
}

export interface ARow {
    szSessionToken: string;
    bHome: number;
}

// {
//     "nResult": "0", "aResultSet" : [{ "aRow": [{ "szSessionToken": "FzCWMJPveZmGYd0DkcZr63F7CnTzJAy3x-s-kGrzIKlz-8c4", "bHome": 0 }], "nTotalRows": 1, "aField": [{ "sName": "szSessionToken", "oMin": "FzCWMJPveZmGYd0DkcZr63F7CnTzJAy3x-s-kGrzIKlz-8c4", "oMax": "FzCWMJPveZmGYd0DkcZr63F7CnTzJAy3x-s-kGrzIKlz-8c4", "sType": "String", "bNumeric": false }, { "sName": "bHome", "oMin": 0, "oMax": 0, "sType": "Byte", "bNumeric": true }] }]
// }
